apiVersion: v1
kind: Service
metadata:
  name: {{ include "orocommerce.fullname" . }}-database
  labels:
    {{- include "orocommerce.labels" . | nindent 4 }}
    component: database
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    {{- include "orocommerce.selectorLabels" . | nindent 4 }}
    component: database
