apiVersion: v1
kind: Service
metadata:
  name: {{ include "orocommerce.fullname" . }}-phpfpm
  labels:
    {{- include "orocommerce.labels" . | nindent 4 }}
    component: phpfpm
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: phpfpm
    protocol: TCP
    name: phpfpm
  selector:
    {{- include "orocommerce.selectorLabels" . | nindent 4 }}
    component: phpfpm 